### ISSUE TITLE
See what's wrong with counter-reformation:

### ISSUE THREAD

**Issue by Zemurin** [ParadoxGameConverters/CK2ToEU4#165]
https://forum.paradoxplaza.com/forum/threads/ck2-to-eu4-converter-release-thread.1377860/page-14#post-26730020

**Comment by IohannesIohannium** [comment]
What does the post say?

**Comment by Zemurin** [comment]
Nothing concrete, waiting on the user to upload their conversion mod.

**Comment by Zemurin** [comment]
Fixed by #185.
