### ISSUE TITLE
Enable the C++ Core Guidelines Checker

### ISSUE THREAD

**Issue by Idhrendur** [ParadoxGameConverters/CK2ToEU4#2]
Instructions for Visual Studio here: https://docs.microsoft.com/en-us/cpp/code-quality/using-the-cpp-core-guidelines-checkers?view=vs-2019

**Comment by Zemurin** [comment]
done? Please confirm? I have ticked the appropriate box, but that's about it?

**Comment by Idhrendur** [comment]
Should be. If you start seeing new warnings pop up while building that reference the core guidelines (they usually end with letter.number in parenthesis) you know you've got it for certain.
