### ISSUE TITLE
Splitting cultures

### ISSUE THREAD

**Issue by IohannesIohannium** [ParadoxGameConverters/CK2ToEU4#27]
(A reminder for me)
German, French, Italian, Spanish, Latin-Roman, Jewish need to be split accordingly.

**Comment by Zemurin** [comment]
Carantian and bosnian are in EAST slavic group.
bosnians shoud have a sunni religion requirement
frankish are germanic
greek need to be broken down
two lombards exist - germanic and latin

**Comment by Zemurin** [comment]
"For German, remind me of having to add Elsäßisch and Sudetisch. For that Muscovite... I'll find something"

**Comment by Zemurin** [comment]
"I'll plan to split Greek into Greek, Anatolian, Magnagreek (Italy)"

**Comment by IohannesIohannium** [comment]
Also: split Bedouins also in Maghreb and Spain, just to be sure.
Remember to add a French-Arabic culture (What-if-Charles-Martel-did-not-exist)
Splitting Latin-Roman and Jewish cultures all over the old world.

**Comment by Zemurin** [comment]
"Berbers below the Sahara should becomes Tuaregs"

**Comment by IohannesIohannium** [comment]
Superseeded by #60
