### ISSUE TITLE
On the HRE

### ISSUE THREAD

**Issue by IohannesIohannium** [ParadoxGameConverters/CK2ToEU4#29]
Currently, nothing is done besides splitting the Empire.

All provinces held by the Empire should get the line `hre = yes` inside.
All the history files of the Electors should get the line `elector = yes` inside.
history/diplomacy/hre.txt should have this line as content: `500.1.1 = { emperor = [Emperor's Tag] } `

How to determine the Electors?
Search among the generated vassals of the HRE (and the Emperor himself).
Find the three theocracies whose rulers hold the highest piety and add them as electors.
Then find the four non-theocracies whose rulers hold the highest amount of prestige and add them as electors.

**Comment by Zemurin** [comment]
"If nobody has the HRE, you have to output three dashes as the ruler of the HRE in that diplomacy file"
