### ISSUE TITLE
Province tax, production and manpower

### ISSUE THREAD

**Issue by IohannesIohannium** [ParadoxGameConverters/CK2ToEU4#30]
Where should we have them from?

**Comment by Idhrendur** [comment]
From my experience with CK2 to EU3, this will be rough. CK2 tends towards very evenly-balanced provinces, whereas EU4 prefers high variability. Although hospitals and great works might help here.

One thing I tried and that helped (but not enough) is having capitals steal development from the underlying titles. It'll probably take some experimenting and number-crunching to get it right.

**Comment by Zemurin** [comment]
We've taken them from barony types and number of buildings inside (where every building upgrade counts as its own building). Castles to mil/adm, temples to adm and cities to dip.
