### ISSUE TITLE
accepted Cultures same as Primary cultures

### ISSUE THREAD

**Issue by CPPX1018** [ParadoxGameConverters/CK2ToEU4#332]
Converter adds accepted culture lines for countries without a second culture, adding an accepted culture for its primary culture, such as north France having primary culture of cosmopolitan French, and accepting culture of cosmopolitan french, affecting about more than half the countries from the converter. Pls add a toggle for accepted culture or fix the feature ty.

**Comment by Zemurin** [comment]
To fix I need to reproduce. Please upload save on forums, thanx.

**Comment by Zemurin** [comment]
Also upload log.txt.

**Comment by CPPX1018** [comment]
Very sorry for the late reply, here should be the log.txt, I have the save as a .txt, but that's because Github doesn't allow the save to be uploade
[Ironman_Mongol_Empireaere345345r.ck2.txt](https://github.com/ParadoxGameConverters/CK2ToEU4/files/7798206/Ironman_Mongol_Empireaere345345r.ck2.txt)
[log.txt](https://github.com/ParadoxGameConverters/CK2ToEU4/files/7798207/log.txt)

d

**Comment by Zemurin** [comment]
Thanx, this is now fixed and merged.
