### ISSUE TITLE
Unhandled unknown exception

### ISSUE THREAD

**Issue by LunatiK-ExpiX** [ParadoxGameConverters/CK2ToEU4#507]
Getting the Unhandled unknown exception after exiting the program once I put in the CK2 documents directory. Reinstalling does nothing, requiring you to wipe the file. It requires a different bug to happen, where if you put a onedrive link into the CK2 documents folder, it causes an Unhandled exception. I can't use the converter until these bugs are fixed

**Comment by Zemurin** [comment]
You haven't uploaded conversion log.txt, ck2 save, or screenshots of the exception. Please go to the forums and upload all of those so I can try and reproduce the issue. 
Normally Onedrive folders are ok-ish, but not always. It depends more on the computer configuration, antivirus protections etc than on the converters which don't care one bit where they read the stuff from.
