### ISSUE TITLE
Women in history

### ISSUE THREAD

**Issue by Zemurin** [ParadoxGameConverters/CK2ToEU4#76]
See if it's possible to increase chance of female advisor generation for countries that have tolerance laws. Maybe this won't be possible if it's hardcoded globally.

**Comment by IohannesIohannium** [comment]
EU4 female advisor generation is coded to be the same for all countries

**Comment by ha-sky** [comment]
very good

**Comment by ha-sky** [comment]
### ****

> 1

**Comment by ha-sky** [comment]
- 1

**Comment by ha-sky** [comment]
1. 1

**Comment by ha-sky** [comment]
- [ ] 1
